platform:
  folder: /home/project/xupf/Databases/NUS8/CANON1D2/RAW
  filename: A95I4940.CR2
  disable_progress_bar: false
  leave_pbar_string: false
sensor_info:
  bayer_pattern: rggb
  sensor_range: '13391'
  bitdep: '13'
  width: '5568'
  height: '3708'
crop:
  isEnable: false
  isDebug: false
  new_width: 256
  new_height: 256
dead_pixel_correction:
  isEnable: false
  dp_threshold: 80
  isDebug: true
black_level_correction:
  isEnable: true
  r_offset: '2047'
  gr_offset: '2047'
  gb_offset: '2047'
  b_offset: '2047'
  isLinear: false
  r_sat: '14888'
  gr_sat: '14888'
  gb_sat: '14888'
  b_sat: '14888'
lens_shading_correction:
  isEnable: false
white_balance:
  isEnable: true
  isAuto: true
demosaic:
  isEnable: true
auto_white_balance:
  isDebug: true
  algorithm: norm_2
  percentage: 3.5
